routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use Spatie\Sitemap\SitemapGenerator;
use App\Models\PageModel;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','Front\DynamisController@index');
Route::get('/home','Front\DynamisController@index');

Route::get('/contac_us', function () {
    return view('contact_us');
});
Route::get('/demo-page',function(){
    return view('layout.master');
});
Route::get('/test-front','Front\DynamisController@index');
Route::get('/content/{id}','Front\DynamisController@contentDetail')->name('front.content.detail');
// Route::get('/content/{id}','Front\DynamisController@contentDetail')->name('front.content.detail');
Route::get('/test-curl','JadwalSholatController@getJadwalSholat');



Route::get("generate-sitemap", function () {

    SitemapGenerator::create("https://itinventorybeacukai.com/")->writeToFile(public_path('sitemap.xml'));
    dd("done");
});


Route::prefix('/admin')->name('admin.')->namespace('Admin')->group(function(){
    
    /**
     * Admin Auth Route(s)
     */
    Route::namespace('Auth')->group(function(){
        
        //Login Routes
        Route::get('/login','LoginController@showLoginForm')->name('login');
        Route::post('/login','LoginController@login')->name('login');
        Route::post('/logout','LoginController@logout')->name('logout');

        //Register Routes
        // Route::get('/register','RegisterController@showRegistrationForm')->name('register');
        // Route::post('/register','RegisterController@register');

        //Forgot Password Routes
        // Route::get('/password/reset','ForgotPasswordController@showLinkRequestForm')->name('password.request');
        // Route::post('/password/email','ForgotPasswordController@sendResetLinkEmail')->name('password.email');

        //Reset Password Routes
        // Route::get('/password/reset/{token}','ResetPasswordController@showResetForm')->name('password.reset');
        // Route::post('/password/reset','ResetPasswordController@reset')->name('password.update');

        // Email Verification Route(s)
        // Route::get('email/verify','VerificationController@show')->name('verification.notice');
        // Route::get('email/verify/{id}','VerificationController@verify')->name('verification.verify');
        // Route::get('email/resend','VerificationController@resend')->name('verification.resend');
        // Route::get('/email/verify/{id}','VerificationController@verify')->name('verification.verify');

    });

    Route::namespace('User')->group(function(){
    	Route::resource('user', 'UserManagementController')->middleware('auth:admin');
    	Route::resource('permission', 'PermissionController')->middleware('auth:admin');
        Route::resource('role', 'RoleController')->middleware('auth:admin');
        Route::resource('content', 'ContentController');

    });
    Route::namespace('Ads')->group(function(){
        Route::resource('adsmanager', 'AdsManagerController');

    });
    Route::namespace('Page')->group(function(){
        Route::resource('page', 'PageController');
        Route::delete('page/delete_menu/{id}','PageController@destroyMenu');
        Route::get('pagelayoutcontent/{id}','PageLayoutContentController@index')->name('pagelayoutcontent.index');
        Route::get('pagelayoutcontent/{id}/create','PageLayoutContentController@create')->name('pagelayoutcontent.create');
        Route::get('pagelayoutcontent/{id}/edit','PageLayoutContentController@edit')->name('pagelayoutcontent.edit');
        Route::patch('pagelayoutcontent/update','PageLayoutContentController@update')->name('pagelayoutcontent.update');
        Route::get('pagelayoutcontent/{id}/destroy','PageLayoutContentController@destroy')->name('pagelayoutcontent.destroy');
        Route::post('pagelayoutcontent/store','PageLayoutContentController@store')->name('pagelayoutcontent.store');

    });

    Route::get('/sukses',function(){
        return "sukses login";
    })->name('sukses');
});

$paths = ['/it','/about_us','/services','/products','/clients','/supports'];
// Route::get('/jadwalsholat','Front\DynamisController@pencarianJadwalSholat');
Route::get('/jadwalsholat','Front\DynamisController@indexSchedule');
Route::get('/generate-ai/artikel', 'Front\DynamisController@getArtikel');

try {
    $pages = PageModel::get();
    foreach ($pages as $page) {
        $paths[] = $page->URL;
    }
} catch (Exception $e) {
    echo '*************************************' . PHP_EOL;
    echo 'Error fetching database pages: ' . PHP_EOL;
    echo $e->getMessage() . PHP_EOL;
    echo '*************************************' . PHP_EOL;
}

foreach($paths as $path){
    $router->get($path, 'Front\DynamisController@index');
    $router->get($path."/{kota_id}", 'Front\DynamisController@index_kota');
    // $router->get($path."/{kota_id}/{tanggal}", 'Front\DynamisController@index_kota_tanggal');
}

app/Http/Controllers/Admin/Ads/AdsManagerController.php
<?php

namespace App\Http\Controllers\Admin\Ads;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\AdsManagerModel;
use App\Models\AdsMediaModel;

use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

use DB;
use DataTables;
use Carbon\Carbon;

class AdsManagerController extends Controller
{
    public function __construct()
    {
        $this->title = 'Content';
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $title = $this->title;

        if($request->ajax())
        {
            $data = AdsManagerModel::orderBy('id','DESC')->get();
            
            return DataTables::of($data)
                ->addColumn('action', function($data){
                    $button = '<div class="btn-group m-t-15">';
                        $button .= '<button type="button" class="btn btn-sm btn-default dropdown-toggle waves-effect waves-light" data-toggle="dropdown" aria-expanded="false">Action</button>';
                        $button .='<div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">';
                            $button .= '<a class="dropdown-item" href="'.route('admin.adsmanager.edit', $data->id).'"><i class="fa fa-pencil"></i> Edit</a>';
                            $button .= '<a class="dropdown-item delete" href="#" id="'.$data->id.'"><i class="fa fa-trash"></i> Delete</a>';
                        $button .= '</div>';
                    $button .= '</div>';
                    return $button;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('admin.ads.index', compact('title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title = $this->title;
        $list_ukuran = [
            'col-md-1' => '12 kolom 1 baris',
            'col-md-2' => '6 kolom 1 baris',
            'col-md-3' => '4 kolom 1 baris',
            'col-md-4' => '3 kolom 1 baris',
            'col-md-5' => '2+1 kolom 1 baris',
            'col-md-6' => '2 kolom 1 baris',
            'col-md-7' => '1 kolom + 2 kolom kecil 1 baris',
            'col-md-8' => '1 kolom + 2 kolom kecil 1 baris',
            'col-md-9' => '1 kolom + 2 kolom kecil 1 baris',
            'col-md-10' => '1 kolom + 1 kolom kecil 1 baris',
            'col-md-11' => '1 kolom + 1 kolom kecil 1 baris',
            'col-md-12' => '1 kolom 1 baris',
        ];
        return view('admin.ads.create', compact('title','list_ukuran'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validator($request);
        
        \DB::beginTransaction();
        try {
            $input = ['Title' => $request->input('Title'),'Content' => $request->input('Content'),
            'IsPrimary' => $request->input('IsPrimary'),'StartPeriod' => $request->input('StartPeriod'),
            'EndPeriod' => $request->input('EndPeriod'),'Name' => $request->input('Name'),
            'Email' => $request->input('Email'),'PhoneNo' => $request->input('PhoneNo'),'AdsFee' => $request->input('AdsFee'),
            'IsVerified' => $request->input('IsVerified')];

            $input['StartPeriod'] = Carbon::parse($request->input('StartPeriod'))->format('Y-m-d');
            $input['EndPeriod'] = Carbon::parse($request->input('EndPeriod'))->format('Y-m-d');

            if($request->has('ShortContent') && $request->ShortContent !== ''){
                $input['ShortContent'] = strip_tags($request->ShortContent);
            }
            if($request->has('Location') && $request->Location !== ''){
                $input['Location'] = $request->Location;
            }
            if($request->has('DestinationURL') && $request->DestinationURL !== ''){
                $input['DestinationURL'] = $request->DestinationURL;
            }
            if($request->has('IDContent') && $request->IDContent !== ''){
                $input['IDContent'] = $request->IDContent;
            }
            if($request->has('Currency') && $request->Currency !== ''){
                $input['Currency'] = $request->Currency;
            }
            if($request->has('CurrencySign') && $request->CurrencySign !== ''){
                $input['CurrencySign'] = $request->CurrencySign;
            }
            if($request->has('boostrap_class') && $request->boostrap_class !== ''){
                $input['boostrap_class'] = $request->boostrap_class;
            }
            $content = AdsManagerModel::create($input);
            if ($content) {
                if($request->hasFile('upload_file')){
                    $image = $request->file('upload_file')->getClientOriginalName();
                    $ext = $request->file('upload_file')->getClientOriginalExtension();
                    $image = 'images/adsmedia/'.Carbon::now()->timestamp.'_'.str_replace(' ','-',$image);
                    Storage::disk('public')->put($image, file_get_contents($request->file('upload_file')->getRealPath()));

                    $articleMedia = new AdsMediaModel();
                    $articleMedia->Location = $image;
                    $articleMedia->IsCover = 'y';
					$articleMedia->SortNo = 1;
                    $articleMedia->id_media = $content->id;
                    $articleMedia->IsPrimary = 'y';
                    $articleMedia->save();
                }
                
                $redirect = redirect()->route('admin.adsmanager.index');
                back()->with('success',trans('message.create.success'));
                \DB::commit();
                return $redirect;
            }
        } catch (\Exception $e) {
            $message = $e->getMessage();
            dd($message);
            \DB::rollback();
            back()->with('error',trans('message.create.error') . ' : ' . $e->getMessage());
            return redirect()->back()->withInput();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $title = $this->title;
        $startPeriod = '00-00-0000';
        $endPeriod = '00-00-0000';
        $listdata = AdsManagerModel::find($id);
        if(!empty($listdata)){
            $startPeriod = Carbon::parse($listdata->StartPeriod)->format('Y-m-d');
            $endPeriod = Carbon::parse($listdata->EndPeriod)->format('Y-m-d');
        }
        $list_ukuran = [
            'col-md-1' => '12 kolom 1 baris',
            'col-md-2' => '6 kolom 1 baris',
            'col-md-3' => '4 kolom 1 baris',
            'col-md-4' => '3 kolom 1 baris',
            'col-md-5' => '2+1 kolom 1 baris',
            'col-md-6' => '2 kolom 1 baris',
            'col-md-7' => '1 kolom + 2 kolom kecil 1 baris',
            'col-md-8' => '1 kolom + 2 kolom kecil 1 baris',
            'col-md-9' => '1 kolom + 2 kolom kecil 1 baris',
            'col-md-10' => '1 kolom + 1 kolom kecil 1 baris',
            'col-md-11' => '1 kolom + 1 kolom kecil 1 baris',
            'col-md-12' => '1 kolom 1 baris',
        ];
        return view('admin.ads.edit',compact('listdata','title','startPeriod','endPeriod','list_ukuran'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'Title' => 'required',
            'Content' => 'required',
            'IsPrimary' => 'required',
            'StartPeriod' => 'required',
            'EndPeriod' => 'required',
            'Name' => 'required',
            'Email' => 'required',
            'PhoneNo' => 'required',
            'AdsFee' => 'required',
            'IsVerified' => 'required',
        ]);

        \DB::beginTransaction();
        try {

            $update = AdsManagerModel::find($id);
            $input = ['Title' => $request->input('Title'),'Content' => $request->input('Content'),
            'IsPrimary' => $request->input('IsPrimary'),'StartPeriod' => $request->input('StartPeriod'),
            'EndPeriod' => $request->input('EndPeriod'),'Name' => $request->input('Name'),
            'Email' => $request->input('Email'),'PhoneNo' => $request->input('PhoneNo'),'AdsFee' => $request->input('AdsFee'),
            'IsVerified' => $request->input('IsVerified')];

            $input['StartPeriod'] = Carbon::parse($request->input('StartPeriod'))->format('Y-m-d');
            $input['EndPeriod'] = Carbon::parse($request->input('EndPeriod'))->format('Y-m-d');

            if($request->has('ShortContent') && $request->ShortContent !== ''){
                $input['ShortContent'] = strip_tags($request->ShortContent);
            }
            if($request->has('Location') && $request->Location !== ''){
                $input['Location'] = $request->Location;
            }
            if($request->has('DestinationURL') && $request->DestinationURL !== ''){
                $input['DestinationURL'] = $request->DestinationURL;
            }
            if($request->has('IDContent') && $request->IDContent !== ''){
                $input['IDContent'] = $request->IDContent;
            }
            if($request->has('Currency') && $request->Currency !== ''){
                $input['Currency'] = $request->Currency;
            }
            if($request->has('CurrencySign') && $request->CurrencySign !== ''){
                $input['CurrencySign'] = $request->CurrencySign;
            }
            if($request->has('boostrap_class') && $request->boostrap_class !== ''){

resources/views/admin/ads/index.blade.php
@extends('layout.master')
@section('css')
<link href="{{ asset('plugins/datatables/dataTables.bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
@endsection
@section('content')

<!-- Start content -->
<div class="content">
    <div class="container-fluid">
        @include('flash-message')
        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="btn-group pull-right m-t-15">
                    <a href="{{url(route('admin.adsmanager.create'))}}" class="btn btn-success waves-effect waves-light">
                        <i class="fa fa-plus"></i> Manage Ads
                    </a>
                </div>

                <h4 class="page-title">Datatable</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Ubold</a></li>
                    <li class="breadcrumb-item"><a href="#">Tables</a></li>
                    <li class="breadcrumb-item active">Datatable</li>
                </ol>

            </div>
        </div>


        <div class="row">
            <div class="col-12">
                <div class="card-box table-responsive">
                    <h4 class="m-t-0 header-title">Data Role</h4>
                    <table id="datatableContent" class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Client Name</th>
                                <th>Fee</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>
                          <tr>
                              <td colspan="4"></td>
                          </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div> <!-- end row -->

    </div> <!-- container -->

</div> <!-- content -->

    <!--  Modal content for the above example -->
    <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="confirmModal" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myLargeModalLabel">Confirmation Delete Data</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                    <h6>Are you sure want to delete this data ?</h6>
                </div>
                <div class="modal-footer">
                    <button type="button" name="ok_button" id="ok_button" class="btn btn-danger">OK</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

@endsection

@section('js')
    <!-- Required datatable js -->
    <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js')}}"></script>

    <!-- Buttons examples -->
    <script src="{{ asset('plugins/datatables/dataTables.buttons.min.js')}}"></script>

    <script>
    $(document).ready(function(){
        var dataTable = $('#datatableContent').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,
            language: {
                searchPlaceholder: '{{ trans('form.text_search') }}',
                sSearch: '',
                lengthMenu: '_MENU_ items/{{ trans('form.text_page') }}',
            },
            ajax: {
                url: "{{ route('admin.adsmanager.index') }}",
                data: function(data){
                }
            },
            columns: [
                {
                    data: 'Title',
                    name: 'Title'
                },
                {
                    data: 'Name',
                    name: 'Name'
                },
                {
                    data: 'AdsFee',
                    name: 'AdsFee'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                }
            ],
            columnDefs: [
                {
                    render: function (data, type, full, meta) {
                        return "<div class='text-wrap width-150'>" + data + "</div>";
                    },
                    targets: 0
                }
             ]
        });
        // $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });

        var listid;
        
        $(document).on('click', '.delete', function(){
            listid = $(this).attr('id');
            $('#confirmModal').modal('show');
        });
        
        $('#ok_button').click(function(){
            var token = $("meta[name='csrf-token']").attr("content");
            $.ajax({
                url:"adsmanager/"+listid,
                type: 'DELETE',
                data: {
                    "id": listid,
                    "_token": token,
                },
                beforeSend:function(){
                    $('#ok_button').text('{{ trans('form.text_deleting') }}');
                },
                success:function(data)
                {
                    setTimeout(function(){
                        $('#confirmModal').modal('hide');
                        $('#datatableRole').DataTable().ajax.reload();
                        $('#ok_button').text('OK');
                    }, 500);
                }
            })
        });

    });
    </script>
@endsection