routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use Spatie\Sitemap\SitemapGenerator;
use App\Models\PageModel;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','Front\DynamisController@index');
Route::get('/home','Front\DynamisController@index');

Route::get('/contac_us', function () {
    return view('contact_us');
});
Route::get('/demo-page',function(){
    return view('layout.master');
});
Route::get('/test-front','Front\DynamisController@index');
Route::get('/content/{id}','Front\DynamisController@contentDetail')->name('front.content.detail');
// Route::get('/content/{id}','Front\DynamisController@contentDetail')->name('front.content.detail');
Route::get('/test-curl','JadwalSholatController@getJadwalSholat');



Route::get("generate-sitemap", function () {

    SitemapGenerator::create("https://itinventorybeacukai.com/")->writeToFile(public_path('sitemap.xml'));
    dd("done");
});


Route::prefix('/admin')->name('admin.')->namespace('Admin')->group(function(){
    
    /**
     * Admin Auth Route(s)
     */
    Route::namespace('Auth')->group(function(){
        
        //Login Routes
        Route::get('/login','LoginController@showLoginForm')->name('login');
        Route::post('/login','LoginController@login')->name('login');
        Route::post('/logout','LoginController@logout')->name('logout');

        //Register Routes
        // Route::get('/register','RegisterController@showRegistrationForm')->name('register');
        // Route::post('/register','RegisterController@register');

        //Forgot Password Routes
        // Route::get('/password/reset','ForgotPasswordController@showLinkRequestForm')->name('password.request');
        // Route::post('/password/email','ForgotPasswordController@sendResetLinkEmail')->name('password.email');

        //Reset Password Routes
        // Route::get('/password/reset/{token}','ResetPasswordController@showResetForm')->name('password.reset');
        // Route::post('/password/reset','ResetPasswordController@reset')->name('password.update');

        // Email Verification Route(s)
        // Route::get('email/verify','VerificationController@show')->name('verification.notice');
        // Route::get('email/verify/{id}','VerificationController@verify')->name('verification.verify');
        // Route::get('email/resend','VerificationController@resend')->name('verification.resend');
        // Route::get('/email/verify/{id}','VerificationController@verify')->name('verification.verify');

    });

    Route::namespace('User')->group(function(){
    	Route::resource('user', 'UserManagementController')->middleware('auth:admin');
    	Route::resource('permission', 'PermissionController')->middleware('auth:admin');
        Route::resource('role', 'RoleController')->middleware('auth:admin');
        Route::resource('content', 'ContentController');

    });
    Route::namespace('Ads')->group(function(){
        Route::resource('adsmanager', 'AdsManagerController');

    });
    Route::namespace('Page')->group(function(){
        Route::resource('page', 'PageController');
        Route::delete('page/delete_menu/{id}','PageController@destroyMenu');
        Route::get('pagelayoutcontent/{id}','PageLayoutContentController@index')->name('pagelayoutcontent.index');
        Route::get('pagelayoutcontent/{id}/create','PageLayoutContentController@create')->name('pagelayoutcontent.create');
        Route::get('pagelayoutcontent/{id}/edit','PageLayoutContentController@edit')->name('pagelayoutcontent.edit');
        Route::patch('pagelayoutcontent/update','PageLayoutContentController@update')->name('pagelayoutcontent.update');
        Route::get('pagelayoutcontent/{id}/destroy','PageLayoutContentController@destroy')->name('pagelayoutcontent.destroy');
        Route::post('pagelayoutcontent/store','PageLayoutContentController@store')->name('pagelayoutcontent.store');

    });

    Route::get('/sukses',function(){
        return "sukses login";
    })->name('sukses');
});

$paths = ['/it','/about_us','/services','/products','/clients','/supports'];
// Route::get('/jadwalsholat','Front\DynamisController@pencarianJadwalSholat');
Route::get('/jadwalsholat','Front\DynamisController@indexSchedule');
Route::get('/generate-ai/artikel', 'Front\DynamisController@getArtikel');

try {
    $pages = PageModel::get();
    foreach ($pages as $page) {
        $paths[] = $page->URL;
    }
} catch (Exception $e) {
    echo '*************************************' . PHP_EOL;
    echo 'Error fetching database pages: ' . PHP_EOL;
    echo $e->getMessage() . PHP_EOL;
    echo '*************************************' . PHP_EOL;
}

foreach($paths as $path){
    $router->get($path, 'Front\DynamisController@index');
    $router->get($path."/{kota_id}", 'Front\DynamisController@index_kota');
    // $router->get($path."/{kota_id}/{tanggal}", 'Front\DynamisController@index_kota_tanggal');
}

resources/views/admin/page/create.blade.php
@extends('layout.master')
@section('content')

<!-- Start content -->
<div class="content">
    <div class="container-fluid">

        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <h4 class="page-title">Datatable</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Ubold</a></li>
                    <li class="breadcrumb-item"><a href="#">Page</a></li>
                    <li class="breadcrumb-item active">Create</li>
                </ol>

            </div>
        </div>
        {!! Form::open(array('route' => 'admin.page.store','method'=>'POST')) !!}
        <div class="row">
            <div class="col-12">
                <div class="card-box table-responsive">
                    <h4 class="m-t-0 header-title">Add Data Page</h4>
                    <div class="form-group row">
                        <label class="col-2 col-form-label">Name</label>
                        <div class="col-10">
                            {!! Form::text('Name', null, array('placeholder' => 'input Name','class' => 'form-control')) !!}
                            @if ($errors->has('Name'))
                                <p class="text-danger">{{ $errors->first('Name') }}</p>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-2 col-form-label">URL</label>
                        <div class="col-10">
                            {!! Form::text('URL', null, array('placeholder' => 'input URL','class' => 'form-control','id'=>'URL')) !!}
                            @if ($errors->has('URL'))
                                <p class="text-danger">{{ $errors->first('URL') }}</p>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-2 col-form-label">Description</label>
                        <div class="col-10">
                            {!! Form::textarea('description', null, array('placeholder' => 'input description','class' => 'form-control','id'=>'description')) !!}
                            @if ($errors->has('description'))
                                <p class="text-danger">{{ $errors->first('description') }}</p>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-2 col-form-label">Keyword</label>
                        <div class="col-10">
                            {!! Form::textarea('keyword', null, array('placeholder' => 'input keyword','class' => 'form-control','id'=>'keyword')) !!}
                            @if ($errors->has('keyword'))
                                <p class="text-danger">{{ $errors->first('keyword') }}</p>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div> <!-- end row -->

        <!-- menu dinamis -->
        <div class="row">
            <div class="col-12">
                <div class="card-box">
                    <div class="row">
                        <div class="col-md-12">
                            <h4 class="m-t-0 header-title">Menus</h4>
                            <div class="form-group">
                                <table class="">
                                    <tr>
                                        <td>
                                            <input type="text" name="menu_name" id="menu_name" class="form-control" placeholder="menu name">
                                        </td>
                                        <td>
                                            <input type="text" name="menu_url" id="menu_url" class="form-control" placeholder="url">
                                        </td>
                                        <td>
                                            Is Default <input type="checkbox" name="menu_default" id="menu_default">
                                        </td>
                                        <td>
                                            <a href="#tabel-body-menu" class="btn btn-primary btn-sm" id="btn-add-menu" data-no="1"><i class="fa fa-plus"></i></a>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="form-group">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Menu name</th>
                                            <th>Url Address</th>
                                            <th>Remove</th>
                                        </tr>
                                    </thead>
                                    <tbody id="tabel-body-menu">
                                        <!-- <tr id="">
                                            <td>
                                                <input type="hidden" name="menu_item[][menu_name]">
                                            </td>
                                            <td>
                                                <input type="hidden" name="menu_item[][menu_url]">
                                            </td>
                                            <td>
                                                <button class="btn btn-danger btn-sm" data-no="1"><i class="fa fa-trash"></i></button>
                                            </td>
                                        </tr> -->
                                    </tbody>
                                </table>
                            </div>

                            <hr>
                            <!-- input menu dinamis -->
                            <div class="form-group">
                                <!-- <label class="col-2 col-form-label" >Last Name</label> -->
                                <div class="col-10">
                                    <button class="btn btn-danger waves-effect waves-light"> <i class="fa fa-close m-r-5"></i> <span>Cancel</span> </button>
                                    <button class="btn btn-default waves-effect waves-light"> <i class="fa fa-heart m-r-5"></i> <span>Submit</span> </button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div> <!-- end card-box -->
            </div> <!-- end col -->
        </div>
        {!! Form::close() !!}

    </div> <!-- container -->

</div> <!-- content -->

@endsection
@section('js')
    
<script>
        var removeMenu = function(id){
            $('#menu-'+id).remove();
        }
        $('#btn-add-menu').click(function(){
            var menu_name = $('#menu_name').val();
            var menu_url = $('#menu_url').val();
            var kunci =  $('#btn-add-menu').attr('data-no');
            var html = '';
            html +='<tr id="menu-'+kunci+'">';
                html +='<td>'
                    html += menu_name;
                    html +='<input type="hidden" name="menu_items['+kunci+'][menu_name]" value="'+menu_name+'">';
                    html +='</td>';
                html +='<td>';
                    html += menu_url;
                    html +='<input type="hidden" name="menu_items['+kunci+'][menu_url]" value="'+menu_url+'">';
                html +='</td>';
                html +='<td>';
                    html +='<a href="#tabel-body-menu" class="btn btn-danger btn-sm" onclick="removeMenu('+kunci+')"><i class="fa fa-trash"></i></a>';
                html +='</td>';
            html +='</tr>';
            $('#menu_name').val('');
            $('#menu_url').val('');
            kunci = parseInt(kunci)+1;
            $('#btn-add-menu').attr('data-no',kunci);
            $('#tabel-body-menu').append(html);
        });
    </script>
@endsection

resources/views/admin/page/edit.blade.php
@extends('layout.master')
@section('content')

<!-- Start content -->
<div class="content">
    <div class="container-fluid">

        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <h4 class="page-title">Datatable</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Ubold</a></li>
                    <li class="breadcrumb-item"><a href="#">Page</a></li>
                    <li class="breadcrumb-item active">Edit</li>
                </ol>

            </div>
        </div>
        {!! Form::model($listdata, ['method' => 'PATCH','route' => ['admin.page.update', $listdata->ID]]) !!}
        <div class="row">
            <div class="col-12">
                <div class="card-box table-responsive">
                    <h4 class="m-t-0 header-title">Edit Data Page</h4>
                    <div class="form-group row">
                        <label class="col-2 col-form-label">Name</label>
                        <div class="col-10">
                            {!! Form::text('Name', null, array('placeholder' => 'input Name','class' => 'form-control')) !!}
                            @if ($errors->has('Name'))
                                <p class="text-danger">{{ $errors->first('Name') }}</p>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-2 col-form-label">URL</label>
                        <div class="col-10">
                            {!! Form::text('URL', null, array('placeholder' => 'input URL','class' => 'form-control','id'=>'URL')) !!}
                            @if ($errors->has('URL'))
                                <p class="text-danger">{{ $errors->first('URL') }}</p>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-2 col-form-label">Description</label>
                        <div class="col-10">
                            {!! Form::textarea('description', null, array('placeholder' => 'input description','class' => 'form-control','id'=>'description')) !!}
                            @if ($errors->has('description'))
                                <p class="text-danger">{{ $errors->first('description') }}</p>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-2 col-form-label">Keyword</label>
                        <div class="col-10">
                            {!! Form::textarea('keyword', null, array('placeholder' => 'input keyword','class' => 'form-control','id'=>'keyword')) !!}
                            @if ($errors->has('keyword'))
                                <p class="text-danger">{{ $errors->first('keyword') }}</p>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div> <!-- end row -->

        <div class="row">
            <div class="col-12">
                <div class="card-box">
                    <div class="row">
                        <div class="col-md-12">
                            <h4 class="m-t-0 header-title">Menus</h4>
                            <div class="form-group">
                                <table class="">
                                    <tr>
                                        <td>
                                            <input type="text" name="menu_name" id="menu_name" class="form-control" placeholder="menu name">
                                        </td>
                                        <td>
                                            <input type="text" name="menu_url" id="menu_url" class="form-control" placeholder="url">
                                        </td>
                                        <td>
                                            Is Default <input type="checkbox" name="menu_default" id="menu_default" @if($is_default == 1)checked @endif>
                                        </td>
                                        <td>
                                            @if(!empty($menu_items))
                                                <a href="#tabel-body-menu" class="btn btn-primary btn-sm" id="btn-add-menu" data-no="{{$menu_items->count()+1}}"><i class="fa fa-plus"></i></a>
                                            @else
                                                <a href="#tabel-body-menu" class="btn btn-primary btn-sm" id="btn-add-menu" data-no="1"><i class="fa fa-plus"></i></a>
                                            @endif
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="form-group">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Menu name</th>
                                            <th>Url Address</th>
                                            <th>Remove</th>
                                        </tr>
                                    </thead>
                                    <tbody id="tabel-body-menu">
                                        @if(!empty($menu_items))
                                            @foreach($menu_items as $item)
                                                <tr id="menu-{{$loop->iteration}}">
                                                    <td>
                                                        {{$item->menu_name}}
                                                        <input type="hidden" name="menu_items[{{$loop->iteration}}]" value="{{$item->ID}}" id="menu-id-{{$loop->iteration}}">
                                                        <input type="hidden" name="menu_items[{{$loop->iteration}}][menu_name]" value="{{$item->menu_name}}">
                                                    </td>
                                                    <td>
                                                        {{$item->menu_url}}
                                                        <input type="hidden" name="menu_items[{{$loop->iteration}}][menu_url]" value="{{$item->menu_url}}">
                                                    </td>
                                                    <td>
                                                        <a href="#tabel-body-menu" class="btn btn-danger btn-sm" onclick="removeMenu({{$loop->iteration}})"><i class="fa fa-trash"></i></a>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        @endif
                                    </tbody>
                                </table>
                            </div>

                            <hr>
                            <!-- input menu dinamis -->
                            <div class="form-group">
                                <!-- <label class="col-2 col-form-label" >Last Name</label> -->
                                <div class="col-10">
                                    <button class="btn btn-danger waves-effect waves-light"> <i class="fa fa-close m-r-5"></i> <span>Cancel</span> </button>
                                    <button class="btn btn-default waves-effect waves-light"> <i class="fa fa-heart m-r-5"></i> <span>Submit</span> </button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div> <!-- end card-box -->
            </div> <!-- end col -->
        </div>
        {!! Form::close() !!}
    </div> <!-- container -->

</div> <!-- content -->

@endsection
@section('js')
    <script>
        var removeMenu = function(id){
            var menuId = $('#menu-id-'+id).val();
            var token = $("meta[name='csrf-token']").attr("content");
            $('#menu-'+id).remove();
            $.ajax({
                url:"{{url('admin/page/delete_menu')}}/"+menuId,
                type: 'DELETE',
                data: {
                    "id": menuId,
                    "_token": token,
                },
                success:function(data)
                {

                }
            })
        }
        $('#btn-add-menu').click(function(){
            var menu_name = $('#menu_name').val();
            var menu_url = $('#menu_url').val();
            var kunci =  $('#btn-add-menu').attr('data-no');
            var html = '';
            html +='<tr id="menu-'+kunci+'">';
                html +='<td>'
                    html += menu_name;
                    html +='<input type="hidden" name="menu_items['+kunci+'][menu_name]" value="'+menu_name+'">';
                    html +='</td>';
                html +='<td>';
                    html += menu_url;
                    html +='<input type="hidden" name="menu_items['+kunci+'][menu_url]" value="'+menu_url+'">';
                html +='</td>';
                html +='<td>';
                    html +='<a href="#tabel-body-menu" class="btn btn-danger btn-sm" onclick="removeMenu('+kunci+')"><i class="fa fa-trash"></i></a>';
                html +='</td>';
            html +='</tr>';
            $('#menu_name').val('');
            $('#menu_url').val('');
            kunci = parseInt(kunci)+1;
            $('#btn-add-menu').attr('data-no',kunci);
            $('#tabel-body-menu').append(html);
        });
    </script>
@endsection

resources/views/admin/page/index.blade.php
@extends('layout.master')
@section('css')
<link href="{{ asset('plugins/datatables/dataTables.bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
@endsection
@section('content')

<!-- Start content -->
<div class="content">
    <div class="container-fluid">
        @include('flash-message')
        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="btn-group pull-right m-t-15">
                    <a href="{{url(route('admin.page.create'))}}" class="btn btn-success waves-effect waves-light">
                        <i class="fa fa-plus"></i> Add Page
                    </a>
                </div>

                <h4 class="page-title">Datatable</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Ubold</a></li>
                    <li class="breadcrumb-item active"><a href="#">Page</a></li>
                    <!-- <li class="breadcrumb-item active">Page</li> -->
                </ol>

            </div>
        </div>


        <div class="row">
            <div class="col-12">
                <div class="card-box table-responsive">
                    <h4 class="m-t-0 header-title">Data Page</h4>
                    <table id="datatablePage" class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>URL</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>
                          <tr>
                              <td colspan="3"></td>
                          </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div> <!-- end row -->

    </div> <!-- container -->

</div> <!-- content -->

    <!--  Modal content for the above example -->
    <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="confirmModal" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myLargeModalLabel">Confirmation Delete Data</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                    <h6>Are you sure want to delete this data ?</h6>
                </div>
                <div class="modal-footer">
                    <button type="button" name="ok_button" id="ok_button" class="btn btn-danger">OK</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

@endsection

@section('js')
    <!-- Required datatable js -->
    <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js')}}"></script>

    <!-- Buttons examples -->
    <script src="{{ asset('plugins/datatables/dataTables.buttons.min.js')}}"></script>

    <script>
    $(document).ready(function(){
        var dataTable = $('#datatablePage').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,
            language: {
                searchPlaceholder: '{{ trans('form.text_search') }}',
                sSearch: '',
                lengthMenu: '_MENU_ items/{{ trans('form.text_page') }}',
            },
            ajax: {
                url: "{{ route('admin.page.index') }}",
                data: function(data){
                    // var role = $('#role').val();
                    // var status = $('#status').val();
                    // var date_start = $('#date_start').val();
                    // var date_end = $('#date_end').val();

                    // data.role = role;
                    // data.status = status;
                    // if(date_start !="" && date_end !=""){
                    //     data.searchByDateStart = date_start;
                    //     data.searchByDateEnd = date_end;
                    // }
                    
                }
            },
            columns: [
                {
                    data: 'Name',
                    name: 'Name'
                },
                {
                    data: 'URL',
                    name: 'URL'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                }
            ],
            columnDefs: [
                {
                    render: function (data, type, full, meta) {
                        return "<div class='text-wrap width-150'>" + data + "</div>";
                    },
                    targets: 0
                }
             ]
        });
        // $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });

        var listid;
        
        $(document).on('click', '.delete', function(){
            listid = $(this).attr('id');
            $('#confirmModal').modal('show');
        });
        
        $('#ok_button').click(function(){
            var token = $("meta[name='csrf-token']").attr("content");
            $.ajax({
                url:"page/"+listid,
                type: 'DELETE',
                data: {
                    "id": listid,
                    "_token": token,
                },
                beforeSend:function(){
                    $('#ok_button').text('{{ trans('form.text_deleting') }}');
                },
                success:function(data)
                {
                    setTimeout(function(){
                        $('#confirmModal').modal('hide');
                        $('#datatableRole').DataTable().ajax.reload();
                        $('#ok_button').text('OK');
                    }, 500);
                }
            })
        });

    });
    </script>
@endsection