routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use Spatie\Sitemap\SitemapGenerator;
use App\Models\PageModel;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','Front\DynamisController@index');
Route::get('/home','Front\DynamisController@index');

Route::get('/contac_us', function () {
    return view('contact_us');
});
Route::get('/demo-page',function(){
    return view('layout.master');
});
Route::get('/test-front','Front\DynamisController@index');
Route::get('/content/{id}','Front\DynamisController@contentDetail')->name('front.content.detail');
// Route::get('/content/{id}','Front\DynamisController@contentDetail')->name('front.content.detail');
Route::get('/test-curl','JadwalSholatController@getJadwalSholat');



Route::get("generate-sitemap", function () {

    SitemapGenerator::create("https://itinventorybeacukai.com/")->writeToFile(public_path('sitemap.xml'));
    dd("done");
});


Route::prefix('/admin')->name('admin.')->namespace('Admin')->group(function(){
    
    /**
     * Admin Auth Route(s)
     */
    Route::namespace('Auth')->group(function(){
        
        //Login Routes
        Route::get('/login','LoginController@showLoginForm')->name('login');
        Route::post('/login','LoginController@login')->name('login');
        Route::post('/logout','LoginController@logout')->name('logout');

        //Register Routes
        // Route::get('/register','RegisterController@showRegistrationForm')->name('register');
        // Route::post('/register','RegisterController@register');

        //Forgot Password Routes
        // Route::get('/password/reset','ForgotPasswordController@showLinkRequestForm')->name('password.request');
        // Route::post('/password/email','ForgotPasswordController@sendResetLinkEmail')->name('password.email');

        //Reset Password Routes
        // Route::get('/password/reset/{token}','ResetPasswordController@showResetForm')->name('password.reset');
        // Route::post('/password/reset','ResetPasswordController@reset')->name('password.update');

        // Email Verification Route(s)
        // Route::get('email/verify','VerificationController@show')->name('verification.notice');
        // Route::get('email/verify/{id}','VerificationController@verify')->name('verification.verify');
        // Route::get('email/resend','VerificationController@resend')->name('verification.resend');
        // Route::get('/email/verify/{id}','VerificationController@verify')->name('verification.verify');

    });

    Route::namespace('User')->group(function(){
    	Route::resource('user', 'UserManagementController')->middleware('auth:admin');
    	Route::resource('permission', 'PermissionController')->middleware('auth:admin');
        Route::resource('role', 'RoleController')->middleware('auth:admin');
        Route::resource('content', 'ContentController');

    });
    Route::namespace('Ads')->group(function(){
        Route::resource('adsmanager', 'AdsManagerController');

    });
    Route::namespace('Page')->group(function(){
        Route::resource('page', 'PageController');
        Route::delete('page/delete_menu/{id}','PageController@destroyMenu');
        Route::get('pagelayoutcontent/{id}','PageLayoutContentController@index')->name('pagelayoutcontent.index');
        Route::get('pagelayoutcontent/{id}/create','PageLayoutContentController@create')->name('pagelayoutcontent.create');
        Route::get('pagelayoutcontent/{id}/edit','PageLayoutContentController@edit')->name('pagelayoutcontent.edit');
        Route::patch('pagelayoutcontent/update','PageLayoutContentController@update')->name('pagelayoutcontent.update');
        Route::get('pagelayoutcontent/{id}/destroy','PageLayoutContentController@destroy')->name('pagelayoutcontent.destroy');
        Route::post('pagelayoutcontent/store','PageLayoutContentController@store')->name('pagelayoutcontent.store');

    });

    Route::get('/sukses',function(){
        return "sukses login";
    })->name('sukses');
});

$paths = ['/it','/about_us','/services','/products','/clients','/supports'];
// Route::get('/jadwalsholat','Front\DynamisController@pencarianJadwalSholat');
Route::get('/jadwalsholat','Front\DynamisController@indexSchedule');
Route::get('/generate-ai/artikel', 'Front\DynamisController@getArtikel');

try {
    $pages = PageModel::get();
    foreach ($pages as $page) {
        $paths[] = $page->URL;
    }
} catch (Exception $e) {
    echo '*************************************' . PHP_EOL;
    echo 'Error fetching database pages: ' . PHP_EOL;
    echo $e->getMessage() . PHP_EOL;
    echo '*************************************' . PHP_EOL;
}

foreach($paths as $path){
    $router->get($path, 'Front\DynamisController@index');
    $router->get($path."/{kota_id}", 'Front\DynamisController@index_kota');
    // $router->get($path."/{kota_id}/{tanggal}", 'Front\DynamisController@index_kota_tanggal');
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Permission\Models\Role;
use Hash;

class User extends Authenticatable
{
    use Notifiable, HasRoles;
    protected $guard_name = 'admin';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'login_name', 'email', 'password', 'first_name', 'last_name', 'is_active','avatar','timezone','language'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getFullNameAttribute($value)
    {
        return "{$this->first_name} {$this->last_name}";
    }

    public function setPasswordAttribute($input)
    {
        if ($input){
            $this->attributes['password'] = app('hash')->needsRehash($input) ? Hash::make($input) : $input;
        }
    }
    
    public function role()
    {
        return $this->belongsToMany(Role::class, 'role_user');
    }

    public function canAny(array $permissions)
    {
        foreach($permissions as $e){
            if($this->can($e)){
                return true;
            } 
        }

        return false;
    }

    public function canAll(array $permissions)
    {
        foreach($permissions as $e){
            if(!$this->can($e)){
                return false;
            } 
        }

        return true;
    }
}

app/Http/Controllers/Admin/User/ContentController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\ContentModel;
use App\Models\ContentMediaModel;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use DB;
use DataTables;
use Carbon\Carbon;

class ContentController extends Controller
{
    public function __construct()
    {
        $this->title = 'Content';
    }

	
	 public function index(Request $request){
        $title = $this->title;

        if($request->ajax())
        {
            $data = ContentModel::orderBy('id','DESC')->get();
            
            return DataTables::of($data)
                ->addColumn('action', function($data){
                    $button = '<div class="btn-group m-t-15">';
                        $button .= '<button type="button" class="btn btn-sm btn-default dropdown-toggle waves-effect waves-light" data-toggle="dropdown" aria-expanded="false">Action</button>';
                        $button .='<div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">';
                            $button .= '<a class="dropdown-item" href="'.route('admin.content.edit', $data->ID).'"><i class="fa fa-pencil"></i> Edit</a>';
                            $button .= '<a class="dropdown-item delete" href="#" id="'.$data->ID.'"><i class="fa fa-trash"></i> Delete</a>';
                        $button .= '</div>';
                    $button .= '</div>';
                    return $button;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('admin.content.index', compact('title'));
    }

    public function create()
    {
        $title = $this->title;
        $listContents = ContentModel::pluck('Title','Title')->all();
        return view('admin.content.create', compact('title','listContents'));
    }

    public function store(Request $request)
    {
        $this->validator($request);
        
        \DB::beginTransaction();
        try {
            $input = ['Title' => $request->input('Title'),'slug'=>Str::slug($request->input('Title'), '-')];
            if($request->has('ShortContent') && $request->ShortContent !== ''){
                $input['ShortContent'] = strip_tags($request->ShortContent);
            }
            if($request->has('Content') && $request->Content !== ''){
                $input['Content'] = $request->Content;
            }
            if($request->has('IDPrevArticle') && $request->IDPrevArticle !== ''){
                $input['IDPrevArticle'] = $request->IDPrevArticle;
            }
            if($request->has('IDNextArticle') && $request->IDNextArticle !== ''){
                $input['IDNextArticle'] = $request->IDNextArticle;
            }
            if($request->has('SourceURL') && $request->SourceURL !== ''){
                $input['SourceURL'] = $request->SourceURL;
            }
            if($request->has('IsPublished') && $request->IsPublished !== ''){
                $input['IsPublished'] = $request->IsPublished;
            }
            if($request->has('keyword') && $request->keyword !== ''){
                $input['keyword'] = $request->keyword;
            }
            if($request->has('meta_description') && $request->meta_description !== ''){
                $input['meta_description'] = $request->meta_description;
            }
            $content = ContentModel::create($input);
            if ($content) {
                if($request->hasFile('upload_file')){
                    $image = $request->file('upload_file')->getClientOriginalName();
                    $ext = $request->file('upload_file')->getClientOriginalExtension();
                    $image = 'images/contents/'.Carbon::now()->timestamp.'_'.str_replace(' ','-',$image);
                    Storage::disk('public')->put($image, file_get_contents($request->file('upload_file')->getRealPath()));

                    $articleMedia = new ContentMediaModel();
                    $articleMedia->URL = $image;
					$articleMedia->SortNo = 1;
                    $articleMedia->IDContent = $content->ID;
                    $articleMedia->IsPrimary = 1;
					$articleMedia->AddedTime = time();
					$articleMedia->AddedByIP = $request->ip();
					$articleMedia->EditedTime = time();
					$articleMedia->EditedByIP = $request->ip();
                    $articleMedia->Type = 'Image';
                    $articleMedia->save();
                }
                
                $redirect = redirect()->route('admin.content.index');
                back()->with('success',trans('message.create.success'));
                \DB::commit();
                return $redirect;
            }
        } catch (\Exception $e) {
            $message = $e->getMessage();
            dd($message);
            \DB::rollback();
            back()->with('error',trans('message.create.error') . ' : ' . $e->getMessage());
            return redirect()->back()->withInput();
        }
    }

    public function edit($id)
    {
        $title = $this->title;
        $listdata = ContentModel::find($id);
        $listContents = ContentModel::pluck('Title','Title')->all();
        return view('admin.content.edit',compact('listdata','title','listContents'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'Title' => 'required|unique:contents,Title,'.$id
        ]);

        \DB::beginTransaction();
        try {

            $update = ContentModel::find($id);
            $input = ['Title' => $request->input('Title')];
            if($request->has('ShortContent') && $request->ShortContent !== ''){
                $input['ShortContent'] = strip_tags($request->ShortContent);
            }
            if($request->has('Content') && $request->Content !== ''){
                $input['Content'] = $request->Content;
            }
            if($request->has('IDPrevArticle') && $request->IDPrevArticle !== ''){
                $input['IDPrevArticle'] = $request->IDPrevArticle;
            }
            if($request->has('IDNextArticle') && $request->IDNextArticle !== ''){
                $input['IDNextArticle'] = $request->IDNextArticle;
            }
            if($request->has('SourceURL') && $request->SourceURL !== ''){
                $input['SourceURL'] = $request->SourceURL;
            }
            if($request->has('IsPublished') && $request->IsPublished !== ''){
                $input['IsPublished'] = $request->IsPublished;
            }
            if($request->has('keyword') && $request->keyword !== ''){
                $input['keyword'] = $request->keyword;
            }
            if($request->has('meta_description') && $request->meta_description !== ''){
                $input['meta_description'] = $request->meta_description;
            }
            $update->update($input);

            if ($update) {

                if($request->hasFile('upload_file')){
                    $articleMedia = ContentMediaModel::where('IDContent',$id)->first();
                    $image = $request->file('upload_file')->getClientOriginalName();
                    $ext = $request->file('upload_file')->getClientOriginalExtension();
                    $image = 'images/contents/'.Carbon::now()->timestamp.'_'.str_replace(' ','-',$image);
                    Storage::disk('public')->put($image, file_get_contents($request->file('upload_file')->getRealPath()));
                    if(empty($articleMedia)){
                        $articleMedia = new ContentMediaModel();
                        $articleMedia->URL = $image;
                        $articleMedia->SortNo = 1;
                        $articleMedia->IDContent = $id;
                        $articleMedia->IsPrimary = 1;
                        $articleMedia->AddedTime = time();
                        $articleMedia->AddedByIP = $request->ip();
                        $articleMedia->EditedTime = time();
                        $articleMedia->EditedByIP = $request->ip();
                        $articleMedia->Type = 'Image';
                        $articleMedia->save();
                    }else{
                        if($articleMedia->URL !="" && Storage::disk('public')->exists($articleMedia->URL)){
                            Storage::disk('public')->delete($articleMedia->URL);
                        }
                        $articleMedia->URL = $image;
                        $articleMedia->AddedByIP = $request->ip();
                        $articleMedia->EditedTime = time();
                        $articleMedia->EditedByIP = $request->ip();
                        $articleMedia->Type = 'Image';
                        $articleMedia->save();
                    }
                }

                back()->with('success',trans('message.update.success'));
                \DB::commit();
                return redirect()->route( 'admin.content.index' );;
            }
        } catch (\Exception $e) {
            \DB::rollback();
            back()->with('error',trans('message.update.error') . ' : ' . $e->getMessage());
            return redirect()->back()->withInput();
        }
    }

    public function destroy($id, Request $request)
    {
        $data = ContentModel::findOrFail($id);
        $data->delete();
        back()->with('success',trans('message.delete.success'));
    }

    private function validator(Request $request)
    {
        $rules = [
            'Title' => 'required|unique:contents,Title',
            // 'permission' => 'required',
        ];

        $messages = [];

        $request->validate($rules,$messages);
    }
}

resources/views/admin/user/create.blade.php
@extends('layout.master')
@section('css')
    <link rel="stylesheet" href="{{asset('plugins/select2/css/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('plugins/bootstrap-select/css/bootstrap-select.min.css')}}">

@endsection
@section('content')

<!-- Start content -->
<div class="content">
    <div class="container-fluid">

        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <h4 class="page-title">Datatable</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Ubold</a></li>
                    <li class="breadcrumb-item"><a href="#">User</a></li>
                    <li class="breadcrumb-item active">Create</li>
                </ol>

            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card-box table-responsive">
                    <h4 class="m-t-0 header-title">Add Data User</h4>
                    {!! Form::open(array('route' => 'admin.user.store','method'=>'POST','id'=>'form-input-user')) !!}
                    <div class="form-group row">
                        <label class="col-2 col-form-label">Email</label>
                        <div class="col-10">
                            {!! Form::text('email', null, array('placeholder' => 'input email','class' => 'form-control')) !!}
                            @if ($errors->has('email'))
                                <p class="text-danger">{{ $errors->first('email') }}</p>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-2 col-form-label">Login Name</label>
                        <div class="col-10">
                            {!! Form::text('login_name', null, array('placeholder' => 'input login name','class' => 'form-control')) !!}
                            @if ($errors->has('login_name'))
                                <p class="text-danger">{{ $errors->first('login_name') }}</p>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-2 col-form-label" >Password</label>
                        <div class="col-10">
                            {!! Form::text('password', null, array('placeholder' => 'input password','class' => 'form-control')) !!}
                            @if ($errors->has('password'))
                                <p class="text-danger">{{ $errors->first('password') }}</p>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-2 col-form-label" >First Name</label>
                        <div class="col-10">
                            {!! Form::text('first_name', null, array('placeholder' => 'input first name','class' => 'form-control')) !!}
                            @if ($errors->has('first_name'))
                                <p class="text-danger">{{ $errors->first('first_name') }}</p>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-2 col-form-label" >Last Name</label>
                        <div class="col-10">
                            {!! Form::text('last_name', null, array('placeholder' => 'input last name','class' => 'form-control')) !!}
                            @if ($errors->has('last_name'))
                                <p class="text-danger">{{ $errors->first('last_name') }}</p>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-2 col-form-label">Role</label>
                        <div class="col-10">
                                {!! Form::select('roles[]', $roles,[], array('class' => 'select2 select2-multiple','multiple')) !!}
                                @if ($errors->has('roles'))
                                    <p class="text-danger">{{ $errors->first('roles') }}</p>
                                @endif
                        </div>
                    </div>
                    <div class="form-group">
                        <!-- <label class="col-2 col-form-label" >Last Name</label> -->
                        <div class="col-10">
                            <!-- <button class="btn btn-danger waves-effect waves-light"> <i class="fa fa-close m-r-5"></i> <span>Cancel</span> </button> -->
                            <a class="btn btn-default waves-effect waves-light" id="submit"> <i class="fa fa-heart m-r-5"></i> <span>Submit</span> </a>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div> <!-- end row -->

    </div> <!-- container -->

</div> <!-- content -->

@endsection
@section('js')
    <script src="{{asset('plugins/select2/js/select2.min.js')}}"></script>

    <script>
        $(".select2").select2();
        $('#submit').click(function(){
            $('#form-input-user').submit();
        })
    </script>
@endsection

resources/views/admin/user/index.blade.php
@extends('layout.master')
@section('css')
<link href="{{ asset('plugins/datatables/dataTables.bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
@endsection
@section('content')

<!-- Start content -->
<div class="content">
    <div class="container-fluid">
        @include('flash-message')
        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="btn-group pull-right m-t-15">
                    <a href="{{url(route('admin.user.create'))}}" class="btn btn-success waves-effect waves-light">
                        <i class="fa fa-plus"></i> User
                    </a>
                </div>

                <h4 class="page-title">Datatable</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Ubold</a></li>
                    <li class="breadcrumb-item"><a href="#">Tables</a></li>
                    <li class="breadcrumb-item active">Datatable</li>
                </ol>

            </div>
        </div>


        <div class="row">
            <div class="col-12">
                <div class="card-box table-responsive">
                    <h4 class="m-t-0 header-title">Data User</h4>
                    <table id="datatableUser" class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Email</th>
                                <th>Login Name</th>
                                <th>Full Name</th>
                                <th>Status</th>
                                <th>Role</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>
                          <tr>
                              <td colspan="6"></td>
                          </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div> <!-- end row -->

    </div> <!-- container -->

</div> <!-- content -->

    <!--  Modal content for the above example -->
    <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="confirmModal" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myLargeModalLabel">Confirmation Delete Data</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                    <h6>Are you sure want to delete this data ?</h6>
                </div>
                <div class="modal-footer">
                    <button type="button" name="ok_button" id="ok_button" class="btn btn-danger">OK</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

@endsection

@section('js')
    <!-- Required datatable js -->
    <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js')}}"></script>

    <!-- Buttons examples -->
    <script src="{{ asset('plugins/datatables/dataTables.buttons.min.js')}}"></script>

    <script>
    $(document).ready(function(){
        var dataTable = $('#datatableUser').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,
            language: {
                searchPlaceholder: '{{ trans('form.text_search') }}',
                sSearch: '',
                lengthMenu: '_MENU_ items/{{ trans('form.text_page') }}',
            },
            ajax: {
                url: "{{ route('admin.user.index') }}",
                data: function(data){
                    // var role = $('#role').val();
                    // var status = $('#status').val();
                    // var date_start = $('#date_start').val();
                    // var date_end = $('#date_end').val();

                    // data.role = role;
                    // data.status = status;
                    // if(date_start !="" && date_end !=""){
                    //     data.searchByDateStart = date_start;
                    //     data.searchByDateEnd = date_end;
                    // }
                    
                }
            },
            columns: [
                {
                    data: 'email',
                    name: 'email'
                },
                {
                    data: 'login_name',
                    name: 'login_name'
                },
                {
                    data: 'full_name',
                    name: 'full_name'
                },
                {
                    data: 'activated',
                    name: 'activated'
                },
                {
                    data: 'role',
                    name: 'role'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                }
            ],
            columnDefs: [
                {
                    render: function (data, type, full, meta) {
                        return "<div class='text-wrap width-150'>" + data + "</div>";
                    },
                    targets: 0
                },
                {
                    render: function (data, type, full, meta) {
                        return "<div class='text-wrap width-150'>" + data + "</div>";
                    },
                    targets: 1
                },
                {
                    render: function (data, type, full, meta) {
                        return "<div class='text-wrap width-150'>" + data + "</div>";
                    },
                    targets: 2
                },
                {
                    render: function (data, type, full, meta) {
                        return "<div class='text-wrap width-150'>" + data + "</div>";
                    },
                    targets: 3
                }
             ]
        });
        // $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });

        var listid;

        // $('.fc-datepicker').datepicker({
        //   showOtherMonths: true,
        //   selectOtherMonths: true,
        //   dateFormat:'yy-mm-dd'
        // });

        
        $(document).on('click', '.delete', function(){
            listid = $(this).attr('id');
            $('#confirmModal').modal('show');
        });
        
        $('#ok_button').click(function(){
            var token = $("meta[name='csrf-token']").attr("content");
            $.ajax({
                url:"user/"+listid,
                type: 'DELETE',
                data: {
                    "id": listid,
                    "_token": token,
                },
                beforeSend:function(){
                    $('#ok_button').text('{{ trans('form.text_deleting') }}');
                },
                success:function(data)
                {
                    setTimeout(function(){
                        $('#confirmModal').modal('hide');
                        $('#datatableUser').DataTable().ajax.reload();
                        $('#ok_button').text('OK');
                    }, 500);
                }
            })
        });

        /*$('#role').change(function(){
            dataTable.draw();
        });
        $('#status').change(function(){
            dataTable.draw();
        });
        $('#date_start').change(function(){
            dataTable.draw();
        });
        $('#date_end').change(function(){
            dataTable.draw();
        });
        */
    });
    </script>
@endsection